import pygame

ROTCOUNTERCWEVENT = pygame.USEREVENT + 1
ROTCWEVENT = pygame.USEREVENT + 2
MOVEFORWARDEVENT = pygame.USEREVENT + 3
SPAWNFISHEVENT = pygame.USEREVENT + 4
SPAWNLEFTNETEVENT = pygame.USEREVENT + 4
SPAWNRIGHTNETEVENT = pygame.USEREVENT + 5
FISHCAUGHTEVENT = pygame.USEREVENT + 6
BGMTWOEVENT = pygame.USEREVENT + 7
